#!/bin/sh -x

# "update" release makes it faster to build and release and also allow us
# sort of pin the entire existing working environment if we foresee many
# disruptive updates ahead and we are not ready to absorb them.

# Basically allowing us to still release new key components without being
# impacted by other changing components that we are not ready to deal with.

# Full and clean release are much preferred so this is to be used in last
# resort only, do not abuse.

DATE_TODAY=$(date '+%Y%m%d')
TAG_PREFIX="dockerupdate"
CURRENT_VERSION=$(awk 'NR == 1 { print $1; exit }' RELEASE.txt)
NEW_VERSION="${CURRENT_VERSION}-dockerupdate${DATE_TODAY}"
TAG_NAME="${TAG_PREFIX}-${NEW_VERSION}"

update_ver() {
  FILE="$1"
  sed -i "s@pavics/workflow-tests:$CURRENT_VERSION@pavics/workflow-tests:$NEW_VERSION@g" $FILE
}

update_ver binder/Dockerfile
update_ver Jenkinsfile
update_ver launchcontainer
update_ver launchnotebook

echo "$NEW_VERSION $(date --universal --iso-8601='seconds')" > RELEASE.txt 

git add binder/Dockerfile Jenkinsfile launchcontainer launchnotebook
git status -v
echo "Looks good to commit? (Ctrl-C to abort)"; read a
git commit -m "release: update pavics/workflow-tests:$CURRENT_VERSION → pavics/workflow-tests:$NEW_VERSION"

git show
echo "Looks good to tag? (Ctrl-C to abort)"; read a

git tag $TAG_NAME
echo "Tag is good to push? (Ctrl-C to abort)"; read a

git push
git push --tags
