#!/bin/sh -x

if [ -z "$DOCKER_IMAGE" ]; then
    DOCKER_IMAGE="pavics/workflow-tests:py312-260331-2"
fi

if [ -z "$CONTAINER_NAME" ]; then
    CONTAINER_NAME="birdy"
fi

# allow directly running another command with the launched docker
# (eg: CONTAINER_CMD=testall launchcontainer)
# otherwise, start interactive shell
if [ -z "${CONTAINER_CMD}" ]; then
  CONTAINER_CMD=/bin/bash
fi

USER_ID="$(id -u)"
GROUP_ID="$(id -g)"

# launch with current user UID and GID to not have write permission problems
docker run -it --rm --name $CONTAINER_NAME \
    -v "$(pwd)":"$(pwd)" -u 0:0 -w "$(pwd)" --hostname "$(hostname -f)" \
    $DOCKER_RUN_OPTS \
    $DOCKER_IMAGE \
    bash -c "groupmod -g $GROUP_ID jenkins; \
             usermod -u $USER_ID jenkins; \
             echo 'ENV_PATH PATH=/usr/local/envs/birdy/bin:/opt/conda/bin:/usr/local/bin:/usr/bin:/bin' >> /etc/login.defs; \
             su jenkins -s ${CONTAINER_CMD}"
