#!/bin/sh -x

PORT="$1"

if [ -z "$PORT" ]; then
    PORT=8890
fi

if [ -z "$DOCKER_IMAGE" ]; then
    DOCKER_IMAGE="pavics/workflow-tests:py311-260319"
fi

if [ -z "$ENV_NAME" ]; then
    ENV_NAME="birdy"
fi 

if [ -z "$CONTAINER_NAME" ]; then
    CONTAINER_NAME="birdy-notebook"
fi

USER_ID="$(id -u)"
GROUP_ID="$(id -g)"

# launch with current user UID and GID to not have write permission problems
docker run --rm --name $CONTAINER_NAME \
    -p $PORT:$PORT -u 0:0 -v "$(pwd)":"$(pwd)" --hostname "$(hostname)" -e ENV_NAME=$ENV_NAME \
    $DOCKER_RUN_OPTS \
    $DOCKER_IMAGE \
    bash -c "groupmod -g $GROUP_ID jenkins; \
             usermod -u $USER_ID jenkins; \
             su jenkins -s /bin/bash -c 'jupyter lab --ip=0.0.0.0 --port=$PORT --no-browser'"
