#!/bin/sh -x

TAG_PREFIX="release"
CURRENT_VERSION=$(bump-my-version show current_version)

#WIP

git commit -m "release: update to use image pavics/workflow-tests:$CURRENT_VERSION"
git show
echo "Looks good to tag? (Ctrl-C to abort)"; read a

git tag ${TAG_PREFIX}-${NEW_VER}
echo "Tag is good to push? (Ctrl-C to abort)"; read a

git push
git push --tags
